#!/data/data/com.termux/files/usr/bin/bash
set +e

ROOT="${BOTA_ROOT:-/data/data/com.termux/files/home/BotA}"
CANON="${ROOT}/ops/bota_crontab.canonical"
TMPDIR="${ROOT}/logs/tmp"
LOGDIR="${ROOT}/logs"
mkdir -p "$TMPDIR" "$LOGDIR"

echo "=== INSTALL CANONICAL BOTA CRONTAB ==="
echo "INPUT_TIMESTAMP_LOCAL=$(date '+%Y-%m-%d %H:%M:%S %Z' 2>/dev/null)"
echo "INPUT_TIMESTAMP_UTC=$(date -u '+%Y-%m-%d %H:%M:%S UTC' 2>/dev/null)"
echo "SOURCE=Termux"
echo "SCOPE=BotA"
echo "FILES_REPLACED=NO"
echo "CRONTAB_CHANGED=YES_IF_INSTALL_RC_0"
echo "TELEGRAM_SEND=NO"
echo "COMMIT=NO"
echo "NO_EXIT_COMMANDS=YES"

ABORT=0
CURRENT="${TMPDIR}/crontab.before_canonical_install.$$"
OUT="${TMPDIR}/crontab.canonical_install.$$"
BACKUP="${LOGDIR}/crontab.backup.before_canonical_install_$(date -u +%Y%m%d_%H%M%S).txt"

crontab -l > "$CURRENT" 2>/dev/null
READ_RC=$?
cp "$CURRENT" "$BACKUP" 2>/dev/null

echo "READ_RC=$READ_RC"
echo "BACKUP_CREATED=$BACKUP"

if [ -s "$CANON" ]; then
  echo "CANONICAL_FILE_OK=$CANON"
else
  echo "CANONICAL_FILE_MISSING_OR_EMPTY=$CANON"
  ABORT=1
fi

DIV_COUNT="$(grep -v '^[[:space:]]*#' "$CURRENT" 2>/dev/null | grep -F 'dividend-capture-scanner/run_bot.sh' | wc -l | tr -d ' ')"
echo "CURRENT_DIVIDEND_COUNT=$DIV_COUNT"

if [ "$DIV_COUNT" != "1" ]; then
  echo "ABORT_REASON=dividend scanner count must be exactly 1 before safe preserve"
  ABORT=1
fi

if [ "$ABORT" = "0" ]; then
  python3 - "$CURRENT" "$CANON" "$OUT" <<'PY'
import sys
from pathlib import Path

current_path = Path(sys.argv[1])
canon_path = Path(sys.argv[2])
out_path = Path(sys.argv[3])

current = current_path.read_text(errors="replace").splitlines()
canon = canon_path.read_text(errors="replace").splitlines()

dividend = []
inside = False

for line in current:
    stripped = line.strip()
    if stripped == "# dividend-capture-scanner BEGIN":
        inside = True
    if inside:
        dividend.append(line)
    if stripped == "# dividend-capture-scanner END":
        inside = False

with out_path.open("w", encoding="utf-8") as f:
    f.write("# Generated by tools/install_canonical_crontab.sh\n")
    f.write("# Preserves Dividend Capture Scanner block and installs canonical BotA block.\n\n")
    for line in dividend:
        f.write(line + "\n")
    f.write("\n")
    for line in canon:
        f.write(line + "\n")
PY

  echo
  echo "=== NEW CRONTAB PREVIEW ==="
  nl -ba "$OUT"

  echo
  echo "=== INSTALL ==="
  crontab "$OUT"
  INSTALL_RC=$?
  echo "INSTALL_RC=$INSTALL_RC"

  echo
  echo "=== POST-INSTALL VERIFY ==="
  bash "$ROOT/tools/verify_canonical_crontab.sh"
else
  echo "INSTALL_SKIPPED=YES"
  echo "INSTALL_RC=99"
fi

rm -f "$CURRENT" "$OUT"
